### ISSUE TITLE
I am getting errors with npm install

### ISSUE THREAD

**Issue by steven5clu884** [leopoldodonnell/opencv-electron#3]
I download the zip file, and unzip in my c:\Develop\ subdirectory
IO then rename opencv-electron-master to leopoldodonnellopencv-electron so the other repo https://github.com/justadudewhohacks/opencv-electron  will not confuse me

I start up an administrator cmd window and cd to C:\Develop\leopoldodonnellopencv-electron
I then type npm install
I get the following in my command window
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.

> opencv@5.0.0 install C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv
> node-pre-gyp install --fallback-to-build

node-pre-gyp info it worked if it ends with ok
node-pre-gyp verb cli [
node-pre-gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
node-pre-gyp verb cli   'C:\\Develop\\leopoldodonnellopencv-electron\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp',
node-pre-gyp verb cli   'install',
node-pre-gyp verb cli   '--fallback-to-build'
node-pre-gyp verb cli ]
node-pre-gyp info using node-pre-gyp@0.6.17
node-pre-gyp info using node@12.13.1 | win32 | x64
node-pre-gyp verb command install []
node-pre-gyp info check checked for "C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\build\opencv\v5.0.0\Release\node-v72-win32-x64\opencv.node" (not found)
node-pre-gyp http GET https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v72-win32-x64.tar.gz
node-pre-gyp http 403 https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v72-win32-x64.tar.gz
node-pre-gyp http 403 status code downloading tarball https://node-opencv.s3.amazonaws.com/opencv/v5.0.0/Release/node-v72-win32-x64.tar.gz (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
node-pre-gyp http Connection closed while downloading tarball file (falling back to source compile with node-gyp)
node-pre-gyp verb command build [ 'rebuild' ]
CC:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\utils\find-opencv.js:57
                throw new Error("ERROR: couldn't read the lib directory " + err);
                ^

Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or directory, scandir 'C:\Develop\opencv-master\build\bin\Debug\lib'
    at C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\utils\find-opencv.js:57:23
    at FSReqCallback.oncomplete (fs.js:146:23)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\utils\find-opencv.js:57
                throw new Error("ERROR: couldn't read the lib directory " + err);
                ^

Error: ERROR: couldn't read the lib directory Error: ENOENT: no such file or directory, scandir 'C:\Develop\opencv-master\build\bin\Debug\lib'
    at C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\utils\find-opencv.js:57:23
    at FSReqCallback.oncomplete (fs.js:146:23)
gyp: Call to 'node utils/find-opencv.js --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! gypconfigure error
gyp  ERR!ERR!  configure errorstack
 Error: `gyp` failed with exit code: 1
gypgyp  ERR!ERR!  stackstack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
gyp Error: `gyp` failed with exit code: 1
 gypERR!  ERR!stack      at ChildProcess.emit (events.js:210:5)
stackgyp     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:351:16)
 gypERR!  ERR!stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
 stack     at ChildProcess.emit (events.js:210:5)
gypgyp  ERR!ERR!  stackSystem     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
 Windows_NT 10.0.18363
gypgyp  ERR!ERR!  commandSystem "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Develop\\leopoldodonnellopencv-electron\\node_modules\\opencv\\build\\opencv\\v5.0.0\\Release\\node-v72-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\Develop\\leopoldodonnellopencv-electron\\node_modules\\opencv\\build\\opencv\\v5.0.0\\Release\\node-v72-win32-x64"
 Windows_NT 10.0.18363
gypgyp  ERR!ERR!  cwdcommand C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Develop\\leopoldodonnellopencv-electron\\node_modules\\opencv\\build\\opencv\\v5.0.0\\Release\\node-v72-win32-x64\\opencv.node" "--module_name=opencv" "--module_path=C:\\Develop\\leopoldodonnellopencv-electron\\node_modules\\opencv\\build\\opencv\\v5.0.0\\Release\\node-v72-win32-x64"
gypgyp  ERR!ERR!  node -vcwd v12.13.1
 C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv
gypgyp  ERR!ERR!  node -vnode-gyp -v v12.13.1
 v5.0.5
gypgyp  ERR!ERR!  not oknode-gyp -v
 v5.0.5
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\build\opencv\v5.0.0\Release\node-v72-win32-x64\opencv.node --module_name=opencv --module_path=C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\build\opencv\v5.0.0\Release\node-v72-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Windows_NT 10.0.18363
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Develop\\leopoldodonnellopencv-electron\\node_modules\\opencv\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv
node-pre-gyp ERR! node -v v12.13.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\build\opencv\v5.0.0\Release\node-v72-win32-x64\opencv.node --module_name=opencv --module_path=C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\build\opencv\v5.0.0\Release\node-v72-win32-x64' (1)
npm WARN rollback Rolling back ansi-regex@2.0.0 failed (this is probably harmless): EPERM: operation not permitted, lstat 'C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\node_modules\node-pre-gyp\node_modules\request\node_modules\har-validator\node_modules\chalk\node_modules\strip-ansi\node_modules'
npm WARN rollback Rolling back concat-map@0.0.1 failed (this is probably harmless): EPERM: operation not permitted, scandir 'C:\Develop\leopoldodonnellopencv-electron\node_modules\opencv\node_modules\node-pre-gyp\node_modules\tar-pack\node_modules\fstream-ignore\node_modules\minimatch\node_modules\brace-expansion\node_modules'
npm WARN opencv-electron@0.1.0 No repository field.
npm WARN opencv-electron@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opencv@5.0.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opencv@5.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wizze\AppData\Roaming\npm-cache\_logs\2019-12-15T01_55_03_580Z-debug.log

**Comment by leopoldodonnell** [comment]
Hey @steven5clu884 - Thanks, for looking into this repo. It's been a long, long time since I've given this a look. I am 100% certain its way out of date. Sadly, I do not have time to look into this ATM. 

Please consider updating and offering a PR and I will review and merge.

**Comment by steven5clu884** [comment]
Thank you for your response.
I am not  knowledgeable about npm, electron so I don't know what i will be
able to do.
Best Wishes to you and your loved ones
